### PR TITLE
[GH-51] Added conditional to disallow export in archived channel when it is not visible to users

### LINKED ISSUE #51: Channel export successful on archived channel when viewing archived channels is disabled
When the system setting “Allow users to view archived channels”  is set to false, the channel export should fail. However it currently succeeds. 

Steps to reproduce:
- Install the latest channel export plugin and enable it in System Console, mark “Allow users to view archived channels” as false

- Create a channel, invite user A and note the channel ID

- As a user A, visit [<DOMAIN>/plugins/com.mattermost.plugin-channel-export/api/v1/export?channel_id=<Channel-ID>&format=csv](http://localhost:8065/plugins/com.mattermost.plugin-channel-export/api/v1/export?channel_id=p3jfd5zt3pr1ujkxexxb1zsx3a&format=csv) 

- The channel export file is downloaded

- As system admin archive the channel

- As user A, re-visit that link. The channel export file can still be downloaded.

For now, archived channels should not be included when `Allow users to view archived channels` is false.

See https://mattermost.atlassian.net/browse/MM-60277

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
-  Added conditional to disallow export in archived channel when system setting “Allow users to view archived channels” is set to false

#### Screensots
image

#### Steps to test:
1. Set system console setting “Allow users to view archived channels” is set to false
2. Hit this API from browser with the channel ID of a channel which is archived: http://localhost:8065/plugins/com.mattermost.plugin-channel-export/api/v1/export?channel_id=test-channel-id&format=csv

#### Ticket Link
Fixes #51

### CODE REVIEW

File: server/api.go [hunk 1]
```diff
@@ -143,6 +143,11 @@ func (h *Handler) Export(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	if channel.DeleteAt > 0 && h.plugin.API.GetConfig().TeamSettings.ExperimentalViewArchivedChannels == nil {
```
[the remark this answers is not in the document]
Comment (raghavaggarwal2308) [reply server/api.go]: @wiggin77 Updated the code please re-review

File: server/api.go [hunk 2]
```diff
@@ -143,6 +143,16 @@ func (h *Handler) Export(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
+	areArchivedChannelsVisible := true
+	if h.plugin.API.GetConfig().TeamSettings.ExperimentalViewArchivedChannels == nil || !*h.plugin.API.GetConfig().TeamSettings.ExperimentalViewArchivedChannels {
+		areArchivedChannelsVisible = false
+	}
+
+	if channel.DeleteAt > 0 && !areArchivedChannelsVisible {
+		handleError(w, http.StatusNotFound, "channel '%s' is deleted and not visible anymore", channelID)
```
Comment (wiggin77) [inline server/api.go:152]:
```suggestion
		handleError(w, http.StatusNotFound, "channel '%s' is archived and not visible anymore", channelID)
```

**Review by wiggin77 — APPROVED** [review]

**Comment by wiggin77** [comment]
@raghavaggarwal2308 there is a test failing.

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Fixed testcases and added new test for the enhacement

**Review by wiggin77 — APPROVED** [review]

File: server/api_test.go [hunk 3]
```diff
@@ -497,4 +518,54 @@ func TestHandler(t *testing.T) {
...
+		mockSystem.EXPECT().GetLicense().Return(&model.License{Features: &model.Features{
+			FutureFeatures: &trueValue,
+		}}).Times(2)
+		mockConfiguration.EXPECT().GetConfig().Return(&model.Config{}).Times(1)
+		mockChannel.EXPECT().Get(channelID).Return(&model.Channel{Id: channelID, DeleteAt: 1}, nil).Times(1)
+		mockUser.EXPECT().HasPermissionToChannel(userID, channelID, model.PermissionReadChannel).Return(true).Times(1)
+		mockUser.EXPECT().HasPermissionTo(userID, model.PermissionManageSystem).Return(false).Times(1)
+		mockConfiguration.EXPECT().GetConfig().Return(&model.Config{
+			TeamSettings: model.TeamSettings{
+				ExperimentalViewArchivedChannels: &falseValue,
```
Comment (fmartingr) [inline server/api_test.go:554]: Should we test the other path as well in this case (and others)? (`ExperimentalViewArchivedChannels == true`)

**Comment by raghavaggarwal2308** [comment]
@wiggin77 @fmartingr Can you please add @AayushChaudhary0001 as a reviewed and add the QA label on this PR

**Review by AayushChaudhary0001 — APPROVED** [review]
This PR has been tested for the following scenario:-
- csv file not getting downloaded for archived channel when the users can't see archived channel

The PR was working fine for the above condition, LGTM. Approved
